# Generated by Django 5.2.8 on 2025-11-07 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('description', models.TextField(verbose_name='Описание')),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('open', 'Открыт'),
                            ('in_progress', 'В работе'),
                            ('resolved', 'Решён'),
                        ],
                        default='open',
                        max_length=20,
                        verbose_name='Статус',
                    ),
                ),
                (
                    'source',
                    models.CharField(
                        choices=[
                            ('operator', 'Оператор'),
                            ('monitoring', 'Мониторинг'),
                            ('partner', 'Партнёр'),
                        ],
                        max_length=20,
                        verbose_name='Источник',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Время создания'
                    ),
                ),
            ],
        ),
    ]
